import '@repo/ui/styles.css';
import { Metadata } from 'next';
import { Geist } from 'next/font/google';
import localFont from 'next/font/local';
import SafeAreaProvider from '../components/SafeAreaProvider';
import './globals.css';

const geist = Geist({ subsets: ['latin'] });

const joyrideStd = localFont({
	src: [
		{
			path: '../../public/fonts/JoyrideSTD.otf',
			style: 'normal',
		},
		{
			path: '../../public/fonts/JoyrideSTDItalic.otf',
			style: 'italic',
		},
	],
	variable: '--font-joyride-std',
});

export const metadata: Metadata = {
	title: 'Create Turborepo',
	description: 'Generated by create turbo',
	viewport: {
		width: 'device-width',
		initialScale: 1,
		viewportFit: 'cover',
	},
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={`${geist.className} ${joyrideStd.variable}`}>
				<SafeAreaProvider>
					{/* <div className="h-dvh flex flex-col">
						<Topbar />
						<main className="flex-1 bg-[#0B1013]">{children}</main>
						<Navbar />
					</div> */}
					{children}
				</SafeAreaProvider>
			</body>
		</html>
	);
}
